### PR TITLE
Refactor tasks related to chainlink consumer contracts

### PR DESCRIPTION
**Pull request by fabioDMFerreira**
* Install chainlink hardhat plugins.

### CODE REVIEW

**Comment by brunoluiz** [comment]
Are these plugins officially supported by ChainLink or have you just extracted them yourself? From what it seems, it would tackle https://github.com/smartcontractkit/hardhat-starter-kit/issues/31 (I've opened it on last Friday).

**Comment by brunoluiz** [comment]
I couldn't find the repositories where these packages came from tho (they are not set in the package.json)

**Comment by fabioDMFerreira** [comment]
Thanks for the heads up on the packages repositories @brunoluiz. Now, if you go to the packages pages you should be able to see the source code. All the plugins are in this repo (https://github.com/appliedblockchain/chainlink-consumer). 

BTW in this repo you may also see:
* the contracts in a dedicated package; 
* the package devops that has the hardhat starter kit refactored (https://github.com/appliedblockchain/chainlink-consumer/tree/master/devops).

@pappas999 if it makes sense I can transfer the ownership of the monorepo.

**Comment by pappas999** [comment]
thanks @fabioDMFerreira , really appreciate your work here, loving these contributions. I'm just discussing the npm repo with the team, I'll get back to you soon and get this reviewed

**Comment by pappas999** [comment]
changes look good @fabioDMFerreira , for now, we'll leave the npm regs with your team until we agree on a path moving forward, and if we decide to take ownership of them, we'll reach out

**Pull request merged**
